# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AVMf – An Open Source Framework for the Alternating Variable Method
email: p.mcminn@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  The AVMf is a framework and Java implementation of the Alternating Variable Method (AVM),
  a heuristic local search algorithm that has been applied to several important software
  engineering problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avmframework.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
